name: "Alamofire CI"

on: [push]

jobs:
  macOS:
    name: Test macOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Download Scope
        run: carthage update
      - name: macOS
        run: xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire macOS" -destination "platform=macOS" test
        env:
          SCOPE_DSN: ${{secrets.SCOPE_DSN}}

  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.3,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2
      - name: Download Scope
        run: carthage update
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire iOS" -destination "${{ matrix.destination }}" test
        env:
          SCOPE_DSN: ${{secrets.SCOPE_DSN}}

  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.3,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
      - uses: actions/checkout@v2
      - name: Download Scope
        run: carthage update
      - name: tvOS - ${{ matrix.destination }}
        run: xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire tvOS" -destination "${{ matrix.destination }}" test
        env:
          SCOPE_DSN: ${{secrets.SCOPE_DSN}}
